name: Run Pester Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pester:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            bw_dir: C:\Users\runneradmin\AppData\Local\bitwarden-cli
            pwsh_modules: C:\Users\runneradmin\Documents\PowerShell\Modules
          - os: ubuntu-latest
            bw_dir: /opt/bitwarden-cli
            pwsh_modules: /home/runner/.local/share/powershell/Modules
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bitwraden CLI Cache
      id: bwcacher
      uses: actions/cache@v3
      with:
        path: ${{ matrix.bw_dir }}
        key: ${{ runner.os }}-BitwardenCLI

    - name: Setup PowerShell Module Cache
      id: cacher
      uses: actions/cache@v3
      with:
        path: ${{ matrix.pwsh_modules }}
        key: ${{ runner.os }}-Pester-SecretManagement

    - name: Install PowerShell Dependencies
      if: steps.cacher.outputs.cache-hit != 'true'
      shell: pwsh
      run: Install-PSResource -Name Pester,Microsoft.PowerShell.SecretManagement -Repository PSGallery -Scope CurrentUser -TrustRepository

    - name: Install Bitwarden CLI
      if: steps.bwcacher.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        # Get Latest Version Number
        $res = Invoke-RestMethod "https://github.com/bitwarden/clients/releases.atom"
        $version = ($res.id | Select-String -Pattern "(?<=\/cli-v)([\d.]+)").Matches[0].Value

        # Determine OS string.
        if($IsWindows) { $os = "windows"}
        elseif($IsMacOS) { $os = "macos"}
        elseif($IsLinux) { $os = "linux"}

        # Download file list
        $Downloads = @(
            @{
                Name = "Binary"
                Uri = "https://github.com/bitwarden/clients/releases/download/cli-v$version/bw-$os-$version.zip"
                OutFile = New-TemporaryFile
            },
            @{
                Name = "Checksum"
                Uri = "https://github.com/bitwarden/clients/releases/download/cli-v$version/bw-$os-sha256-$version.txt"
                OutFile = New-TemporaryFile
            }
        )

        # Download files in parallel.
        $jobs = @()
        foreach ($Download in $Downloads) {
            $jobs += Start-ThreadJob -Name $Download.Name -ScriptBlock {
                $params = $using:Download
                Invoke-WebRequest -Uri $params.Uri -OutFile $params.OutFile
            }
        }
        Write-Host "Downloading Bitwarden"
        Receive-Job -Job $jobs -Wait

        $hash = Get-FileHash -Path ($Downloads | Where-Object {$_.Name -eq "Binary"}).OutFile -Algorithm SHA256
        $checksum = Get-Content -Path ($Downloads | Where-Object {$_.Name -eq "Checksum"}).OutFile

        if($hash.Hash -ine $checksum) {
            Write-Error @"
        The SHA256 Hash of the Downloaded Bitwarden CLI Doesn't Match The Provided Checksum!
            Hash: {0}
        Checksum: {1}
        "@ -f $hash.Hash, $checksum
        }
        else {
            if(!(Test-Path -Path "${{ matrix.bw_dir }}" -PathType Container)) {
              New-Item -Path "${{ matrix.bw_dir }}" -ItemType Directory | Out-Null
            }
            # Extract bw from the downloaded zip file.
            Expand-Archive -Path ($Downloads | Where-Object {$_.Name -eq "Binary"}).OutFile -DestinationPath "${{ matrix.bw_dir }}"
            # Cleanup Downloaded Files
            $Downloads.OutFile | Remove-Item
        }

    - name: Run Pester Tests
      shell: pwsh
      working-directory: .
      run: |
        Import-Module Microsoft.PowerShell.SecretManagement
        $env:BITWARDEN_CLI_PATH = (Get-ChildItem -Path "${{ matrix.bw_dir }}" -Filter "bw*" -File).FullName
        # Run Pester tests with Code Coverage
        $config = New-PesterConfiguration
        $config.Run.Path = "."
        $config.CodeCoverage.Enabled = $IsWindows
        $config.CodeCoverage.OutputPath = "coverage.xml"
        $config.TestResult.Enabled = $true
        $config.TestResult.OutputPath = "Unit.Tests.xml"
        $config.Output.Verbosity = "Detailed"
        Invoke-Pester -Configuration $config

    - name: Upload code coverage report
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.xml

    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-Unit-Tests
        path: Unit.Tests.xml
