name: Run Pester Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pester:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Setup PowerShell Module Cache
    #   id: cacher
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.local/share/powershell/Modules
    #     key: ${{ runner.os }}-Pester-SecretManagement

    - name: Install Bitwarden CLI Dependency
      run: npm i @bitwarden/cli -g

    - name: Install Pester
      shell: pwsh
      run: Install-PSResource -Name Pester,Microsoft.PowerShell.SecretManagement -Repository PSGallery -Scope CurrentUser -TrustRepository

    - name: Run Pester Tests
      shell: pwsh
      working-directory: .
      run: |
        # Run Pester tests with Code Coverage
        $config = New-PesterConfiguration
        $config.Run.Path = "."
        $config.CodeCoverage.Enabled = $true
        $config.CodeCoverage.OutputPath = "coverage.xml"
        $config.TestResult.Enabled = $true
        $config.TestResult.OutputPath = "Unit.Tests.xml"
        Invoke-Pester -Configuration $config

    - name: Upload code coverage report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.xml

    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-Unit-Tests
        path: Unit.Tests.xml
